services:
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - agri_pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  wine-collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    env_file:
      - collector/.env
    depends_on:
      - postgres

volumes:
  agri_pgdata: